// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.yaml` | (string & {});
};

export type Admin = {
    id: string;
    role: AdminRole;
    username: string;
};

export type AdminCategory = {
    created_at: string;
    created_by: string;
    id: string;
    name: string;
    updated_at: string;
    updated_by: string;
};

export type AdminInventory = {
    created_at: string;
    created_by: string;
    id: string;
    product_id: string;
    quantity_received: number;
    quantity_remaining: number;
    unit_cost: string;
    updated_at: string;
    updated_by: string;
};

export type AdminProduct = {
    barcode: string;
    category?: string | null;
    category_id?: string | null;
    created_at: string;
    created_by: string;
    description?: string | null;
    id: string;
    image_url?: string | null;
    is_active: boolean;
    name: string;
    quantity_in_stock: number;
    selling_price: string;
    sub_category?: string | null;
    sub_category_id?: string | null;
    updated_at: string;
    updated_by: string;
};

export enum AdminRole {
    SALE_ADMIN = 'sale_admin',
    PLAYGROUND_ADMIN = 'playground_admin',
    SUPER_ADMIN = 'super_admin'
}

export type AdminSale = {
    created_at: string;
    id: string;
    total_amount: string;
};

export type AdminSaleDetails = {
    created_at: string;
    id: string;
    sale_items: Array<SaleItem>;
    total_amount: string;
};

export type CreateCategoryPayload = {
    name: string;
};

export type CreateProductPayload = {
    barcode: string;
    category_id?: string | null;
    description?: string | null;
    image_url?: string | null;
    inventory?: null | NewInventoryPayload;
    is_active: boolean;
    name: string;
    selling_price: string;
    sub_category_id?: string | null;
};

export type LoginRequest = {
    password: string;
    username: string;
};

export type NewInventoryPayload = {
    quantity_received: number;
    unit_cost: string;
};

export type PaginatedResponseAdminProduct = {
    current_page: number;
    data: Array<{
        barcode: string;
        category?: string | null;
        category_id?: string | null;
        created_at: string;
        created_by: string;
        description?: string | null;
        id: string;
        image_url?: string | null;
        is_active: boolean;
        name: string;
        quantity_in_stock: number;
        selling_price: string;
        sub_category?: string | null;
        sub_category_id?: string | null;
        updated_at: string;
        updated_by: string;
    }>;
    total_items: number;
    total_pages: number;
};

export type PaginatedResponseAdminSale = {
    current_page: number;
    data: Array<{
        created_at: string;
        id: string;
        total_amount: string;
    }>;
    total_items: number;
    total_pages: number;
};

export type PaginatedResponseUserProduct = {
    current_page: number;
    data: Array<{
        barcode: string;
        category?: string | null;
        description?: string | null;
        id: string;
        image_url?: string | null;
        name: string;
        quantity_in_stock: number;
        selling_price: string;
        sub_category?: string | null;
    }>;
    total_items: number;
    total_pages: number;
};

export type PaginationQuery = {
    page?: number | null;
    page_size?: number | null;
};

export type ProductFilter = {
    category_id?: string | null;
    query: string;
};

export type ProductSearchParams = {
    barcode?: string | null;
    categories_id?: Array<string> | null;
    max_price?: string | null;
    min_price?: string | null;
    name?: string | null;
    sub_categories_id?: Array<string> | null;
};

export type ProductSearchParamsAdmin = ProductSearchParams & {
    is_active?: boolean | null;
};

export type SaleItem = {
    cost_price: string;
    created_at: string;
    id: string;
    product_id: string;
    product_name: string;
    quantity: number;
    sale_id: string;
    selling_price: string;
};

export type UpdateCategoryPayload = {
    name: string;
    updated_by: string;
};

export type UpdateProductPayload = {
    barcode: string;
    category_id: string;
    description?: string | null;
    image_url?: string | null;
    is_active: boolean;
    name: string;
    selling_price: string;
    sub_category_id?: string | null;
};

export type UserProduct = {
    barcode: string;
    category?: string | null;
    description?: string | null;
    id: string;
    image_url?: string | null;
    name: string;
    quantity_in_stock: number;
    selling_price: string;
    sub_category?: string | null;
};

export type GetAllCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/categories';
};

export type GetAllCategoriesErrors = {
    400: unknown;
    401: unknown;
    409: unknown;
    500: unknown;
};

export type GetAllCategoriesResponses = {
    201: Array<AdminCategory>;
};

export type GetAllCategoriesResponse = GetAllCategoriesResponses[keyof GetAllCategoriesResponses];

export type CreateCategoryData = {
    body: CreateCategoryPayload;
    path?: never;
    query?: never;
    url: '/admin/categories';
};

export type CreateCategoryErrors = {
    400: unknown;
    401: unknown;
    409: unknown;
    500: unknown;
};

export type CreateCategoryResponses = {
    201: AdminCategory;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type UpdateCategoryData = {
    body: UpdateCategoryPayload;
    path?: never;
    query?: never;
    url: '/admin/categories/{id}';
};

export type UpdateCategoryErrors = {
    400: unknown;
    401: unknown;
    409: unknown;
    500: unknown;
};

export type UpdateCategoryResponses = {
    201: AdminCategory;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type InsertInventoryData = {
    body: NewInventoryPayload;
    path: {
        /**
         * Product UUID
         */
        product_id: string;
    };
    query?: never;
    url: '/admin/inventory/{product_id}';
};

export type InsertInventoryErrors = {
    400: unknown;
    401: unknown;
    404: unknown;
    500: unknown;
};

export type InsertInventoryResponses = {
    200: AdminInventory;
};

export type InsertInventoryResponse = InsertInventoryResponses[keyof InsertInventoryResponses];

export type AdminLoginHandlerData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/admin/login';
};

export type AdminLoginHandlerErrors = {
    401: unknown;
};

export type AdminLoginHandlerResponses = {
    200: Admin;
};

export type AdminLoginHandlerResponse = AdminLoginHandlerResponses[keyof AdminLoginHandlerResponses];

export type AdminLogoutHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/logout';
};

export type AdminLogoutHandlerResponses = {
    200: unknown;
};

export type GetProductsPaginatedAdminData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
    };
    url: '/admin/products';
};

export type GetProductsPaginatedAdminErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetProductsPaginatedAdminResponses = {
    /**
     * Paginated list of products
     */
    200: PaginatedResponseUserProduct;
};

export type GetProductsPaginatedAdminResponse = GetProductsPaginatedAdminResponses[keyof GetProductsPaginatedAdminResponses];

export type CreateProductData = {
    body: CreateProductPayload;
    path?: never;
    query?: never;
    url: '/admin/products';
};

export type CreateProductErrors = {
    400: unknown;
    401: unknown;
    409: unknown;
    500: unknown;
};

export type CreateProductResponses = {
    201: AdminProduct;
};

export type CreateProductResponse = CreateProductResponses[keyof CreateProductResponses];

export type GetAllProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/products/all';
};

export type GetAllProductsErrors = {
    401: unknown;
    403: unknown;
};

export type GetAllProductsResponses = {
    200: Array<AdminProduct>;
};

export type GetAllProductsResponse = GetAllProductsResponses[keyof GetAllProductsResponses];

export type FindProductsAdminData = {
    body?: never;
    path?: never;
    query: {
        page?: number;
        page_size?: number;
        query: string;
        category_id?: string;
    };
    url: '/admin/products/search';
};

export type FindProductsAdminErrors = {
    /**
     * Invalid query parameters or JSON payload validation failed
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Forbidden - Requires admin privileges
     */
    403: unknown;
    /**
     * Internal database error
     */
    500: unknown;
};

export type FindProductsAdminResponses = {
    /**
     * Successfully retrieved paginated admin products
     */
    200: PaginatedResponseAdminProduct;
};

export type FindProductsAdminResponse = FindProductsAdminResponses[keyof FindProductsAdminResponses];

export type FindProductsAdminAdvancedData = {
    body: ProductSearchParamsAdmin;
    path?: never;
    query?: {
        /**
         * The page number to retrieve (1-indexed)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
    };
    url: '/admin/products/search/advanced';
};

export type FindProductsAdminAdvancedErrors = {
    /**
     * Invalid query parameters or JSON payload validation failed
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Forbidden - Requires admin privileges
     */
    403: unknown;
    /**
     * Internal database error
     */
    500: unknown;
};

export type FindProductsAdminAdvancedResponses = {
    /**
     * Successfully retrieved paginated admin products
     */
    200: PaginatedResponseAdminProduct;
};

export type FindProductsAdminAdvancedResponse = FindProductsAdminAdvancedResponses[keyof FindProductsAdminAdvancedResponses];

export type DeleteProductData = {
    body?: never;
    path: {
        /**
         * Product UUID
         */
        product_id: string;
    };
    query?: never;
    url: '/admin/products/{product_id}';
};

export type DeleteProductErrors = {
    404: unknown;
    409: unknown;
    500: unknown;
};

export type DeleteProductResponses = {
    204: void;
};

export type DeleteProductResponse = DeleteProductResponses[keyof DeleteProductResponses];

export type GetProductByIdAdminData = {
    body?: never;
    path: {
        /**
         * Product UUID
         */
        product_id: string;
    };
    query?: never;
    url: '/admin/products/{product_id}';
};

export type GetProductByIdAdminErrors = {
    /**
     * Product not found
     */
    404: unknown;
    500: unknown;
};

export type GetProductByIdAdminResponses = {
    200: AdminProduct;
};

export type GetProductByIdAdminResponse = GetProductByIdAdminResponses[keyof GetProductByIdAdminResponses];

export type UpdateProductData = {
    body: UpdateProductPayload;
    path: {
        /**
         * Product UUID
         */
        product_id: string;
    };
    query?: never;
    url: '/admin/products/{product_id}';
};

export type UpdateProductErrors = {
    400: unknown;
    401: unknown;
    404: unknown;
    500: unknown;
};

export type UpdateProductResponses = {
    200: AdminProduct;
};

export type UpdateProductResponse = UpdateProductResponses[keyof UpdateProductResponses];

export type GetSaleDetailByIdData = {
    body?: never;
    path: {
        /**
         * Sale UUID
         */
        sale_id: string;
    };
    query?: never;
    url: '/api/products/{sale_id}';
};

export type GetSaleDetailByIdErrors = {
    /**
     * Sale Detail not found
     */
    404: unknown;
    500: unknown;
};

export type GetSaleDetailByIdResponses = {
    200: AdminSaleDetails;
};

export type GetSaleDetailByIdResponse = GetSaleDetailByIdResponses[keyof GetSaleDetailByIdResponses];

export type GetSalesPaginatedData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
    };
    url: '/api/sales';
};

export type GetSalesPaginatedErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetSalesPaginatedResponses = {
    /**
     * Paginated list of sale records
     */
    200: PaginatedResponseAdminSale;
};

export type GetSalesPaginatedResponse = GetSalesPaginatedResponses[keyof GetSalesPaginatedResponses];
