// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.yaml` | (string & {});
};

export type Admin = {
    delivery_status_values: Array<string>;
    id: string;
    role: AdminRole;
    username: string;
};

export type AdminCategory = {
    created_at: string;
    created_by: string;
    deleted_at?: string | null;
    deleted_by?: string | null;
    id: string;
    is_deleted: boolean;
    name: string;
    updated_at: string;
    updated_by: string;
};

export type AdminInventory = {
    created_at: string;
    created_by: string;
    expiry_date?: string | null;
    id: string;
    product_id: string;
    quantity_received: number;
    quantity_remaining: number;
    received_at: string;
    unit_cost: string;
    updated_at: string;
    updated_by: string;
};

export type AdminProduct = {
    barcode: string;
    category?: string | null;
    category_id?: string | null;
    created_at: string;
    created_by: string;
    description?: string | null;
    id: string;
    image_url?: string | null;
    is_perishable: boolean;
    is_shown_online: boolean;
    name: string;
    quantity_in_stock: number;
    selling_price: string;
    sub_category?: string | null;
    sub_category_id?: string | null;
    updated_at: string;
    updated_by: string;
};

export enum AdminRole {
    SALE_ADMIN = 'sale_admin',
    PLAYGROUND_ADMIN = 'playground_admin',
    SUPER_ADMIN = 'super_admin'
}

export type AdminSale = {
    created_at: string;
    id: string;
    total_amount: string;
};

export type AdminSaleDetails = {
    by_admin?: null | SaleAdminDetail;
    created_at: string;
    id: string;
    is_instore_sale: boolean;
    sale_items: Array<SaleItem>;
    total_amount: string;
};

export type AdminStaff = {
    id: string;
    role: AdminRole;
    username: string;
};

export type CreateAdminSalePayload = {
    sale_products: Array<SaleProduct>;
};

export type CreateCategoryPayload = {
    name: string;
};

export type CreateClaimTokenPayload = {
    total_quantity: number;
    unit_price: string;
};

export type CreateProductPayload = {
    barcode: string;
    category_id?: string | null;
    description?: string | null;
    image_url?: string | null;
    inventory?: null | NewInventoryPayload;
    is_perishable: boolean;
    is_shown_online: boolean;
    name: string;
    selling_price: string;
    sub_category_id?: string | null;
};

export type DeleteCategoryResponse = {
    deleted_at?: string | null;
    deleted_by?: string | null;
    id: string;
    is_deleted: boolean;
};

export enum DeliveryStatus {
    PENDING = 'Pending',
    ON_DELIVERY = 'OnDelivery',
    RECEIVED = 'Received'
}

export type LoginRequest = {
    password: string;
    username: string;
};

export type NewInventoryPayload = {
    expiry_date?: string | null;
    quantity_received: number;
    received_at?: string | null;
    unit_cost: string;
};

export type PaginatedResponseAdminInventory = {
    current_page: number;
    data: Array<{
        created_at: string;
        created_by: string;
        expiry_date?: string | null;
        id: string;
        product_id: string;
        quantity_received: number;
        quantity_remaining: number;
        received_at: string;
        unit_cost: string;
        updated_at: string;
        updated_by: string;
    }>;
    total_items: number;
    total_pages: number;
};

export type PaginatedResponseAdminProduct = {
    current_page: number;
    data: Array<{
        barcode: string;
        category?: string | null;
        category_id?: string | null;
        created_at: string;
        created_by: string;
        description?: string | null;
        id: string;
        image_url?: string | null;
        is_perishable: boolean;
        is_shown_online: boolean;
        name: string;
        quantity_in_stock: number;
        selling_price: string;
        sub_category?: string | null;
        sub_category_id?: string | null;
        updated_at: string;
        updated_by: string;
    }>;
    total_items: number;
    total_pages: number;
};

export type PaginatedResponseAdminSale = {
    current_page: number;
    data: Array<{
        created_at: string;
        id: string;
        total_amount: string;
    }>;
    total_items: number;
    total_pages: number;
};

export type PaginatedResponseUserResponse = {
    current_page: number;
    data: Array<{
        address_line_1?: string | null;
        id: string;
        phone_number?: string | null;
        username: string;
    }>;
    total_items: number;
    total_pages: number;
};

export type PaginationQuery = {
    page?: number | null;
    page_size?: number | null;
};

export type PlaygroundCheckoutDataAdmin = {
    available_coupons: Array<string>;
    claimed_by?: string | null;
    expired: boolean;
    expires_at: string;
    total_price?: string | null;
    total_quantity: number;
    unit_price: string;
};

export type ProductFilter = {
    category_id?: string | null;
    query: string;
};

export type ProductSearchParams = {
    barcode?: string | null;
    categories_id?: Array<string> | null;
    max_price?: string | null;
    min_price?: string | null;
    name?: string | null;
    sub_categories_id?: Array<string> | null;
};

export type ProductSearchParamsAdmin = ProductSearchParams & {
    is_shown_online?: boolean | null;
};

export type SaleAdminDetail = {
    id: string;
    username: string;
};

export type SaleItem = {
    cost_price: string;
    created_at: string;
    id: string;
    product_id: string;
    product_name: string;
    quantity: number;
    sale_id: string;
    selling_price: string;
};

export type SaleProduct = {
    product_id: string;
    quantity: number;
};

export type SaleSummary = {
    avg_basket: string;
    is_instore_sale: boolean;
    items_sold: number;
    margin: string;
    margin_percentage: string;
    sale_date: string;
    total_cost: string;
    total_sale: string;
    transactions: number;
};

export type SaleSummaryFilter = {
    end_date?: string | null;
    start_date?: string | null;
};

export type StockLevel = {
    is_low_stock: boolean;
    product_id: string;
    product_name: string;
    quantity_in_stock: number;
};

export type TicketSaleSummary = {
    free_tickets_redeemed: number;
    sale_date: string;
    tickets_sold: number;
    total_sale: string;
};

export type TicketSaleSummaryFilter = {
    end_date: string;
    start_date: string;
};

export type UpdateCategoryPayload = {
    name: string;
};

export type UpdateOrderDeliveryStatusResponse = {
    delivery_status: DeliveryStatus;
    id: string;
};

export type UpdateOrderTrackingUrlPayload = {
    order_tracking_url: string;
};

export type UpdateProductPayload = {
    barcode: string;
    category_id: string;
    description?: string | null;
    image_url?: string | null;
    is_perishable: boolean;
    is_shown_online: boolean;
    name: string;
    selling_price: string;
    sub_category_id?: string | null;
};

export type UploadResponse = {
    file_url: string;
};

export type UserResponse = {
    address_line_1?: string | null;
    id: string;
    phone_number?: string | null;
    username: string;
};

export type GetAllCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/categories';
};

export type GetAllCategoriesErrors = {
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetAllCategoriesResponses = {
    /**
     * List of all categories
     */
    200: Array<AdminCategory>;
};

export type GetAllCategoriesResponse = GetAllCategoriesResponses[keyof GetAllCategoriesResponses];

export type CreateCategoryData = {
    body: CreateCategoryPayload;
    path?: never;
    query?: never;
    url: '/admin/categories';
};

export type CreateCategoryErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateCategoryResponses = {
    /**
     * Category created
     */
    201: AdminCategory;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        /**
         * Category UUID
         */
        id: string;
    };
    query?: never;
    url: '/admin/categories/{id}';
};

export type DeleteCategoryErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DeleteCategoryResponses = {
    /**
     * Category (soft) deleted
     */
    200: DeleteCategoryResponse;
};

export type DeleteCategoryResponse2 = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type UpdateCategoryData = {
    body: UpdateCategoryPayload;
    path: {
        /**
         * Category UUID
         */
        id: string;
    };
    query?: never;
    url: '/admin/categories/{id}';
};

export type UpdateCategoryErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UpdateCategoryResponses = {
    /**
     * Category updated
     */
    200: AdminCategory;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type GetProductInventoryStockLevelData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/admin/inventory/low-stock';
};

export type GetProductInventoryStockLevelErrors = {
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Forbidden - Insufficient privileges
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetProductInventoryStockLevelResponses = {
    /**
     * Products ordered by stock level
     */
    200: Array<StockLevel>;
};

export type GetProductInventoryStockLevelResponse = GetProductInventoryStockLevelResponses[keyof GetProductInventoryStockLevelResponses];

export type GetProductInventoryRecordsData = {
    body?: never;
    path: {
        /**
         * Product UUID
         */
        product_id: string;
    };
    query?: {
        page?: number;
        page_size?: number;
    };
    url: '/admin/inventory/{product_id}';
};

export type GetProductInventoryRecordsErrors = {
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Product not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetProductInventoryRecordsResponses = {
    /**
     * Paginated inventory records
     */
    200: PaginatedResponseAdminInventory;
};

export type GetProductInventoryRecordsResponse = GetProductInventoryRecordsResponses[keyof GetProductInventoryRecordsResponses];

export type InsertInventoryRecordData = {
    body: NewInventoryPayload;
    path: {
        /**
         * Product UUID
         */
        product_id: string;
    };
    query?: never;
    url: '/admin/inventory/{product_id}';
};

export type InsertInventoryRecordErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Product not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type InsertInventoryRecordResponses = {
    /**
     * Inventory record created
     */
    200: AdminInventory;
};

export type InsertInventoryRecordResponse = InsertInventoryRecordResponses[keyof InsertInventoryRecordResponses];

export type AdminLoginHandlerData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/admin/login';
};

export type AdminLoginHandlerErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type AdminLoginHandlerResponses = {
    /**
     * Authenticated admin details
     */
    200: Admin;
};

export type AdminLoginHandlerResponse = AdminLoginHandlerResponses[keyof AdminLoginHandlerResponses];

export type AdminLogoutHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/logout';
};

export type AdminLogoutHandlerErrors = {
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type AdminLogoutHandlerResponses = {
    /**
     * Session destroyed
     */
    200: unknown;
};

export type UpdateOrderDeliveryStatusData = {
    body?: never;
    path: {
        /**
         * Order ID/UUID
         */
        order_id: string;
    };
    query?: never;
    url: '/admin/orders/update_status/{order_id}';
};

export type UpdateOrderDeliveryStatusErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UpdateOrderDeliveryStatusResponses = {
    /**
     * Order delivery status updated
     */
    200: UpdateOrderDeliveryStatusResponse;
};

export type UpdateOrderDeliveryStatusResponse2 = UpdateOrderDeliveryStatusResponses[keyof UpdateOrderDeliveryStatusResponses];

export type UpdateOrderTrackingUrlHandlerData = {
    body: UpdateOrderTrackingUrlPayload;
    path: {
        /**
         * Order UUID
         */
        order_id: string;
    };
    query?: never;
    url: '/admin/orders/{order_id}';
};

export type UpdateOrderTrackingUrlHandlerErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UpdateOrderTrackingUrlHandlerResponses = {
    /**
     * Order tracking url updated
     */
    200: string;
};

export type UpdateOrderTrackingUrlHandlerResponse = UpdateOrderTrackingUrlHandlerResponses[keyof UpdateOrderTrackingUrlHandlerResponses];

export type GetCheckoutDataAdminData = {
    body?: never;
    path: {
        /**
         * Claim token id
         */
        token_id: string;
    };
    query?: never;
    url: '/admin/playground/checkout/{token_id}';
};

export type GetCheckoutDataAdminErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Forbidden - Insufficient privileges
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetCheckoutDataAdminResponses = {
    /**
     * Claimed Response
     */
    200: PlaygroundCheckoutDataAdmin;
};

export type GetCheckoutDataAdminResponse = GetCheckoutDataAdminResponses[keyof GetCheckoutDataAdminResponses];

export type GetTicketSaleSummaryData = {
    body?: never;
    path?: never;
    query: {
        start_date: string;
        end_date: string;
    };
    url: '/admin/playground/summary';
};

export type GetTicketSaleSummaryErrors = {
    /**
     * Bad request - invalid or inverted date range
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetTicketSaleSummaryResponses = {
    /**
     * Daily ticket sales summary
     */
    200: Array<TicketSaleSummary>;
};

export type GetTicketSaleSummaryResponse = GetTicketSaleSummaryResponses[keyof GetTicketSaleSummaryResponses];

export type CreatPlaygroundTokenData = {
    body: CreateClaimTokenPayload;
    path?: never;
    query?: never;
    url: '/admin/playground/tokens';
};

export type CreatPlaygroundTokenErrors = {
    /**
     * Unauthorized - Missing or invalid Session Cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient privileges
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreatPlaygroundTokenResponses = {
    /**
     * Claim token
     */
    200: string;
};

export type CreatPlaygroundTokenResponse = CreatPlaygroundTokenResponses[keyof CreatPlaygroundTokenResponses];

export type GetProductsPaginatedAdminData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
    };
    url: '/admin/products';
};

export type GetProductsPaginatedAdminErrors = {
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetProductsPaginatedAdminResponses = {
    /**
     * Paginated list of products
     */
    200: PaginatedResponseAdminProduct;
};

export type GetProductsPaginatedAdminResponse = GetProductsPaginatedAdminResponses[keyof GetProductsPaginatedAdminResponses];

export type CreateProductData = {
    body: CreateProductPayload;
    path?: never;
    query?: never;
    url: '/admin/products';
};

export type CreateProductErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Conflict - Product already exists
     */
    409: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateProductResponses = {
    /**
     * Product created
     */
    201: AdminProduct;
};

export type CreateProductResponse = CreateProductResponses[keyof CreateProductResponses];

export type GetAllProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/products/all';
};

export type GetAllProductsErrors = {
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetAllProductsResponses = {
    /**
     * List of all products
     */
    200: Array<AdminProduct>;
};

export type GetAllProductsResponse = GetAllProductsResponses[keyof GetAllProductsResponses];

export type SearchProductsAdminData = {
    body?: never;
    path?: never;
    query: {
        page?: number;
        page_size?: number;
        query: string;
        category_id?: string;
    };
    url: '/admin/products/search';
};

export type SearchProductsAdminErrors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Internal database error
     */
    500: unknown;
};

export type SearchProductsAdminResponses = {
    /**
     * Paginated list of matching products
     */
    200: PaginatedResponseAdminProduct;
};

export type SearchProductsAdminResponse = SearchProductsAdminResponses[keyof SearchProductsAdminResponses];

export type SearchProductsAdminAdvancedData = {
    body: ProductSearchParamsAdmin;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
    };
    url: '/admin/products/search/advanced';
};

export type SearchProductsAdminAdvancedErrors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Internal database error
     */
    500: unknown;
};

export type SearchProductsAdminAdvancedResponses = {
    /**
     * Paginated list of matching products
     */
    200: PaginatedResponseAdminProduct;
};

export type SearchProductsAdminAdvancedResponse = SearchProductsAdminAdvancedResponses[keyof SearchProductsAdminAdvancedResponses];

export type DeleteProductData = {
    body?: never;
    path: {
        /**
         * Product UUID
         */
        product_id: string;
    };
    query?: never;
    url: '/admin/products/{product_id}';
};

export type DeleteProductErrors = {
    /**
     * Product not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DeleteProductResponses = {
    /**
     * Product soft-deleted
     */
    204: void;
};

export type DeleteProductResponse = DeleteProductResponses[keyof DeleteProductResponses];

export type GetProductByIdAdminData = {
    body?: never;
    path: {
        /**
         * Product UUID
         */
        product_id: string;
    };
    query?: never;
    url: '/admin/products/{product_id}';
};

export type GetProductByIdAdminErrors = {
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Product not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetProductByIdAdminResponses = {
    /**
     * Product details
     */
    200: AdminProduct;
};

export type GetProductByIdAdminResponse = GetProductByIdAdminResponses[keyof GetProductByIdAdminResponses];

export type UpdateProductData = {
    body: UpdateProductPayload;
    path: {
        /**
         * Product UUID
         */
        product_id: string;
    };
    query?: never;
    url: '/admin/products/{product_id}';
};

export type UpdateProductErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Product not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UpdateProductResponses = {
    /**
     * Product updated
     */
    200: AdminProduct;
};

export type UpdateProductResponse = UpdateProductResponses[keyof UpdateProductResponses];

export type GetSalesPaginatedData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
    };
    url: '/admin/sales';
};

export type GetSalesPaginatedErrors = {
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetSalesPaginatedResponses = {
    /**
     * Paginated list of sale records
     */
    200: PaginatedResponseAdminSale;
};

export type GetSalesPaginatedResponse = GetSalesPaginatedResponses[keyof GetSalesPaginatedResponses];

export type CreateAdminSaleData = {
    body: CreateAdminSalePayload;
    path?: never;
    query?: never;
    url: '/admin/sales';
};

export type CreateAdminSaleErrors = {
    /**
     * Invalid request or insufficient inventory
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateAdminSaleResponses = {
    /**
     * Sale created
     */
    201: string;
};

export type CreateAdminSaleResponse = CreateAdminSaleResponses[keyof CreateAdminSaleResponses];

export type SaleSummaryData = {
    body?: never;
    path?: never;
    query?: {
        start_date?: string;
        end_date?: string;
    };
    url: '/admin/sales/summary';
};

export type SaleSummaryErrors = {
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type SaleSummaryResponses = {
    /**
     * Daily sales summary
     */
    200: Array<SaleSummary>;
};

export type SaleSummaryResponse = SaleSummaryResponses[keyof SaleSummaryResponses];

export type GetSaleDetailByIdData = {
    body?: never;
    path: {
        /**
         * Sale UUID
         */
        sale_id: string;
    };
    query?: never;
    url: '/admin/sales/{sale_id}';
};

export type GetSaleDetailByIdErrors = {
    /**
     * Forbidden - Missing or invalid session
     */
    403: unknown;
    /**
     * Sale not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetSaleDetailByIdResponses = {
    /**
     * Sale details
     */
    200: AdminSaleDetails;
};

export type GetSaleDetailByIdResponse = GetSaleDetailByIdResponses[keyof GetSaleDetailByIdResponses];

export type GetAllAdminStaffData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/staff';
};

export type GetAllAdminStaffErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetAllAdminStaffResponses = {
    /**
     * All staff
     */
    200: Array<AdminStaff>;
};

export type GetAllAdminStaffResponse = GetAllAdminStaffResponses[keyof GetAllAdminStaffResponses];

export type UploadImageData = {
    /**
     * Multipart form data with 'file' field
     */
    body: string;
    path?: never;
    query?: never;
    url: '/admin/uploads';
};

export type UploadImageErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UploadImageResponses = {
    /**
     * Public file URL
     */
    200: UploadResponse;
};

export type UploadImageResponse = UploadImageResponses[keyof UploadImageResponses];

export type GetAllUsersPaginatedData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
    };
    url: '/admin/users';
};

export type GetAllUsersPaginatedErrors = {
    /**
     * Unauthorized - Missing or invalid session
     */
    401: unknown;
    /**
     * Forbidden - Insufficient privileges
     */
    403: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetAllUsersPaginatedResponses = {
    /**
     * Paginated list of users
     */
    200: PaginatedResponseUserResponse;
};

export type GetAllUsersPaginatedResponse = GetAllUsersPaginatedResponses[keyof GetAllUsersPaginatedResponses];
